version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "Client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "ConnectServer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "GameServer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "JoinServer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "libs/mu-db"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "libs/mu-logger"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "libs/mu-packet-manager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "WebServer/mu-socket-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "WebServer/mu-web-admin"
    schedule:
      interval: "weekly"
