version: '3.7'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muonline
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./.docker-files/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mu

  connectserver:
    build:
      context: ./ConnectServer
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "44405:44405"
      - "55557:55557/udp"
    volumes:
      - ./ConnectServer:/app
    networks:
      - mu

  joinserver:
    build:
      context: ./JoinServer
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - "55970:55970"
    volumes:
      - ./JoinServer:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - mu

  web-admin:
    build:
      context: ./WebServer/mu-web-admin
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./WebServer/mu-web-admin:/app
    networks:
      - mu

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mu

  socketserver:
    build:
      context: ./WebServer/mu-socket-server
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "44404:44404"
    volumes:
      - ./WebServer/mu-socket-server:/app
    networks:
      - mu

networks:
  mu:
    driver: bridge

volumes:
  esdata:
