version: '3.7'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muonline
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./.docker-files/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  connectserver:
    build:
      context: ./ConnectServer
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "44405:44405"
      - "55557:55557/udp"
    volumes:
      - ./ConnectServer:/app

  joinserver:
    build:
      context: ./JoinServer
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - "55970:55970"
    volumes:
      - ./JoinServer:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  web-admin:
    build:
      context: ./WebServer/mu-web-admin
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
