name: Mu Web Admin tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install
        run: |
          cd WebServer/mu-web-admin
          yarn

      - name: Build
        run: |
          cd WebServer/mu-web-admin
          yarn build

      - name: Lint
        run: |
          cd WebServer/mu-web-admin
          yarn lint
